import React,{useState} from "react";
import {createRoot} from "react-dom/client";
import {AnimatePresence,motion} from "motion/react";
import {Activity,ArrowUpRight,Bell,Brain,ChevronRight,Command,FileText,FolderKanban,LayoutDashboard,Menu,MessageSquare,Plus,Search,ShieldCheck,Sparkles,Wallet,X} from "lucide-react";
import "./styles.css";
const nav=[["Overview",<LayoutDashboard/>],["AI Studio",<Brain/>],["Projects",<FolderKanban/>],["Files",<FileText/>],["Automation",<Sparkles/>]];
const cards=[["AI Studio","Orchestrate models, prompts and tools from one place.","12 active workflows",<Brain/>],["Projects","Keep context, files and conversations together.","8 projects",<FolderKanban/>],["Automation","Turn repeatable work into controlled workflows.","3 running",<Sparkles/>],["Security","Monitor account and system protection.","All systems normal",<ShieldCheck/>]];
function App(){const[mobile,setMobile]=useState(false),[active,setActive]=useState("Overview"),[prompt,setPrompt]=useState(""),[sent,setSent]=useState(false);
return <div className="app"><aside className={mobile?"sidebar open":"sidebar"}><div className="brand"><div className="brandmark">X</div><b>XAWD</b><button className="icon close" onClick={()=>setMobile(false)}><X/></button></div><button className="newBtn"><Plus/> New workspace</button><div className="nav">{nav.map(([label,icon])=><button key={label as string} className={active===label?"navItem active":"navItem"} onClick={()=>{setActive(label as string);setMobile(false)}}>{icon}<span>{label as string}</span></button>)}</div><div className="navLabel">SYSTEM</div><button className="navItem"><Wallet/><span>Wallet</span><em>Soon</em></button><button className="navItem"><ShieldCheck/><span>Trust Center</span></button><div className="sidebarBottom"><div className="plan"><span>Free plan</span><b>18%</b><div className="bar"><i/></div><small>Usage resets in 12 days</small></div><div className="profile"><div className="avatar">R</div><div><b>Workspace</b><small>Personal account</small></div><ChevronRight/></div></div></aside>
<main className="main"><header><button className="icon menu" onClick={()=>setMobile(true)}><Menu/></button><div className="crumb">{active}<ChevronRight/><span>Workspace</span></div><div className="headerActions"><button className="search" onClick={()=>document.getElementById("command")?.focus()}><Search/><span>Search</span><kbd>⌘ K</kbd></button><button className="icon"><Bell/></button><div className="avatar">R</div></div></header>
<div className="content"><div className="welcome"><div><span className="eyebrow">YOUR COMMAND CENTER</span><h1>Build something meaningful.</h1><p>Everything you need to think, create and automate — in one calm workspace.</p></div><button className="primary"><Plus/> New project</button></div>
<section className="aiPanel"><div className="aiTop"><div className="aiTitle"><div className="aiIcon"><Sparkles/></div><div><b>AI Command Center</b><small>Multi-model workspace</small></div></div><span className="live"><i/> Ready</span></div><textarea id="command" value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Tell XAWD what you want to accomplish…"/><div className="aiBottom"><div className="chips"><button>Summarize files</button><button>Build a plan</button><button>Analyze data</button></div><button className="run" onClick={()=>setSent(true)}>{sent?"Prepared":"Run"} <ArrowUpRight/></button></div><AnimatePresence>{sent&&<motion.div initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="notice"><Activity/> Request prepared safely. Connect a server-side provider to enable inference.</motion.div>}</AnimatePresence></section>
<div className="sectionHead"><div><h2>Workspace overview</h2><span>Live product signals</span></div><button className="textBtn">View all <ChevronRight/></button></div><section className="cards">{cards.map(([title,desc,meta,icon])=><motion.div whileHover={{y:-3}} className="card" key={title as string}><div className="cardIcon">{icon}</div><h3>{title as string}</h3><p>{desc as string}</p><div className="meta"><span>{meta as string}</span><ArrowUpRight/></div></motion.div>)}</section>
<section className="lower"><div className="activity"><div className="sectionHead"><div><h2>Recent activity</h2><span>Across your workspace</span></div></div>{["AI workflow prepared","New project created","Security check completed"].map((x,i)=><div className="activityRow" key={x}><div className="dot">{i===0?<MessageSquare/>:i===1?<FolderKanban/>:<ShieldCheck/>}</div><div><b>{x}</b><small>{i+2} minutes ago</small></div><ChevronRight/></div>)}</div><div className="health"><div className="sectionHead"><div><h2>System health</h2><span>Real-time status</span></div></div><div className="healthScore"><div className="score">99.9<span>%</span></div><div><b>Everything operational</b><small>Last checked just now</small></div></div>{["Application","API","Authentication","AI Gateway"].map(x=><div className="healthRow" key={x}><span>{x}</span><span className="ok"><i/>Operational</span></div>)}</div></section></div></main><div className="commandHint"><Command/> Quick command</div></div>}
createRoot(document.getElementById("root")!).render(<App/>);